### ISSUE TITLE
Hey 👋 

### ISSUE THREAD

**Issue by JokersCat** [eternalodball/inscreate#2]
So im also doing a Gen with selenium and I finished it I only have to implement proxies maybe we can work together to make a little aio like follow botting and stuff 😊
So yeah if you would like to get in contact with me just command your discord tag

**Comment by eternalodball** [comment]
discord - eternalodball#6241
telegram - @eternalodball
i don't use discord that often so sorry if i give you wrong username

**Comment by JokersCat** [comment]
added you on discord :D

**Comment by eternalodball** [comment]
> added you on discord :D

ok ty
