### ISSUE TITLE
Hey 👋 it’s me again

### ISSUE THREAD

**Issue by JokersCat** [eternalodball/inscreate#3]
So I saw your Update and I have little suggestion. So there are some mail.tm api wrappers around and personally I can suggest Mail Silents Mailtm wrapper it’s really handy and easy to use 😊 and yeah you could speed the process up when you await till the element is useable and then instantly use it. Maybe I could help you with this tomorrow I write you on discord cya

**Comment by eternalodball** [comment]
yes you can always use webdriver wait but i don't cause ,
My code will look messy and difficult to understand by others ,
that's why i used sleep module instead .
